spring.application.name=clinic-booking-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:cbs_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:23042003}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
