spring.application.name=clinic-booking-backend
spring.config.import=optional:file:.env[.properties],optional:file:${user.dir}/.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:cbs_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:}
jwt.expiration-ms=${JWT_EXPIRATION:86400000}
booking.slot-lock-ttl-minutes=${SLOT_LOCK_TTL_MINUTES:5}
booking.lock-sweep-interval-ms=${LOCK_SWEEP_INTERVAL_MS:60000}
